### ISSUE TITLE
[Issue]Rich Presence doesn't support diplayed as Traditional Chinese

### ISSUE THREAD

**Issue by StarskyXIII** [nanite/Simple-Discord-Rich-Presence#26]
### Mod version

3.0.1-build.21+mc1.18.2

### Forge mod loader version

40.1.84

### Repeatable?

- [X] Yes

### Link to log files

https://mclo.gs/XSBBiwH

### Steps to reproduce the issue

1. Lauch FTB Stoneblock 3
2. Apply Traditional Chinese translation by resourcepack
3. Check Discord Rich Presence

### Description of the issue you are having

When I translated mod to Traditional Chinese, Discord Rich Presence will show me the Mojibake
```
{
  "sdrp.logo": "模組包 Logo",
  "sdrp.mainmenu": "主選單",
  "sdrp.overworld.in": "位於主世界",
  "sdrp.overworld": "主世界",
  "sdrp.the_nether.in": "位於地獄",
  "sdrp.the_nether": "地獄",
  "sdrp.the_end.in": "位於終界",
  "sdrp.the_end": "位於終界",
  "sdrp.compact_world.in": "位於壓縮世界",
  "sdrp.compact_world": "壓縮世界",
  "sdrp.dungeon.in": "位於地牢世界",
  "sdrp.dungeon": "地牢世界",
  "sdrp.spatial_storage.in": "位於地牢世界",
  "sdrp.spatial_storage": "地牢世界"
}
```
![support](https://user-images.githubusercontent.com/71606873/201005245-2dc16e24-1093-4387-aa07-6a5c1e6b74ac.png)

### Information

- [X] I have provided as much information as possible

**Comment by Sunekaer** [comment]
Done

**Comment by StarskyXIII** [comment]
Sorry, this is `zh_tw` lang file instead `zh_cn`.

**Comment by Sunekaer** [comment]
woops sorry ill push an update to fix that

**Comment by StarskyXIII** [comment]
And my issue is Rich Presence would not display as Chinese corrently, it will show me the Mojibake

**Comment by Sunekaer** [comment]
I hope its fixed by the updated lang file

**Comment by StarskyXIII** [comment]
I updated the mod to the latest version, still have the same issue :(

**Comment by StarskyXIII** [comment]
If this will not be fixed, please remove the zh_tw lang file.
I'm not hope Taiwanese players playing on the modpack which include this mod always have the same issue.
